apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^todo/', include('todo.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.conf.urls import url
from . import views

app_name = 'todo'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<todo_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^new/$', views.new, name='new'),
    url(r'^delete/(?P<todo_id>[0-9]+)/$', views.delete, name='delete'),
    url(r'^toggle_done/(?P<todo_id>[0-9]+)/$', views.toggle_done, name='toggle_done'),
    url(r'^update/(?P<todo_id>[0-9]+)/$', views.update, name='update'),
    url(r'^comment/(?P<todo_id>[0-9]+)/$', views.comment, name='comment'),

]

todo/models.py
from django.db import models

class Todo(models.Model):
    todo_text = models.CharField(max_length=50)
    todo_done = models.BooleanField(default=0)

    def __str__(self):
        return self.todo_text

    def __bool__(self):
        return self.todo_done


class Comment(models.Model):
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE)
    todo_comment = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.todo_comment

    def __bool__(self):
        return self.todo_done

todo/views.py
from django.shortcuts import render, redirect
from .models import Todo,Comment
from django.http import Http404

def index(request):
    recent_todoes = Todo.objects.all().order_by('-id')
    context = {'recent_todoes': recent_todoes,}
    return render(request, 'todo/index.html', context)

def detail(request, todo_id):
    todo_text = Todo.objects.get(pk=todo_id)
    todoID = Todo.objects.get(pk=todo_id).id
    todoes = Todo.objects.all()
    index = 0
    for t in todoes:
        if (t.id != todoID):
            index += 1
        else:
            break

    if (todoes[index] == Todo.objects.all().last()):
        next_todo_id = todoes[index].id
    else:
        next_todo_id = todoes[index+1].id

    if (todoes[index] == Todo.objects.all().first()):
        prev_todo_id = todoes[index].id
    else:
        prev_todo_id = todoes[index-1].id

    todo_done = todo_text.todo_done
    recent_comments = todo_text.comment_set.all()
    if (recent_comments):
        todo_comment = Comment.objects.get(pk=todo_id)
    else:
        todo_comment = "-"
    context = {'todo_text': todo_text, 'todo_done': todo_done, 'todoID': todoID, 'todo_comment': todo_comment, 'next_todo_id':next_todo_id, 'prev_todo_id':prev_todo_id}
    return render(request, 'todo/detail.html', context)

def new(request):
    if (request.method == 'POST'):
        text = request.POST['todo_text']
        todo = Todo(todo_text=text)
        todo.save()
        return redirect('/todo')
    else:
        return render(request, 'todo/new.html')

def update(request, todo_id):
    try:
        todoID = Todo.objects.get(pk=todo_id).id
        todo = Todo.objects.get(pk=todo_id)
        context = {'todo_text':todo, 'todoID':todoID}
        if (request.method == 'POST'):
            todo.todo_text = request.POST['todo_text']
            todo.save()

    except:
        raise Http404("Todo does not exist!")
    return render(request, 'todo/update.html', context)

#----------------------------------

def delete(request, todo_id):
    text = Todo.objects.get(pk=todo_id)
    text.delete()
    return redirect('/todo')

def toggle_done(request, todo_id):
    todo = Todo.objects.get(pk=todo_id)
    todoID = todo.id
    if (todo.todo_done == 1):
        todo.todo_done = 0
    elif (todo.todo_done == 0):
        todo.todo_done = 1
    todo.save()
    return redirect(request.META.get('HTTP_REFERER')) #redirect('/todo')

def comment(request, todo_id):
    todoID = Todo.objects.get(pk=todo_id).id
    todo = Todo.objects.get(pk=todoID)
    if (request.method == 'POST'):
        comment = todo.comment_set.create(todo_comment=request.POST['todo_comment'])
        comment.id = todoID
        comment.save()

    if (todo.todo_done == 1):
        todo.todo_done = 0
    elif (todo.todo_done == 0):
        todo.todo_done = 1
    todo.save()
    return redirect(request.META.get('HTTP_REFERER'))

todo/templates/todo/detail.html
{% include "todo/header.html"%}

<!--  <body> -->


    <div class="container">
      {% if next_todo_id != todoID %}
        <h1 class="left-arrow"><a href="{% url 'todo:detail' next_todo_id %}"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span></a></h1>
      {% endif %}

      {% if prev_todo_id != todoID %}
        <h1 class="right-arrow"><a href="{% url 'todo:detail' prev_todo_id %}"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a></h1>
      {% endif %}
      <h1 class="text-center"> {{ todo_text }} </h1>
      <br>
      {% if todo_done %}
        Done<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <br><br>
        <p>Comment: {{ todo_comment }}</p>
        <a href="{% url 'todo:toggle_done' todoID %}"><button class="btn btn-warning" type="button" name="button">Not done</button></a>
        <br><br>
      {% else %}
        Not done<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        <br>
        <form action="{% url 'todo:comment' todoID %}" method="post" autocomplete="off">
          {% csrf_token %}
          <input type="text" name="todo_comment" class="form-control" placeholder="Comment your execution...">
          <input class="btn btn-success" type="submit" value="Done">
        </form>
        <br>
      {% endif %}

      <div class="col-md-4">
        <a href="../"><button class="btn btn-info" type="button" name="button">Back</button></a>
      </div>
      <div class="col-md-4">
          <a href="{% url 'todo:delete' todoID %}"><button class="btn btn-danger" type="button">Delete</button></a>
      </div>
      <div class="col-md-4">
        <a href="{% url 'todo:update' todoID %}"><button class="btn btn-primary" type="button">Update</button></a>
      </div>
    </div>

  </body>
</html>

todo/templates/todo/header.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <meta charset="utf-8">
    <title>TODO</title>
    <meta name="viewport" content="width=device-width, height=device-height initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.16.0/jquery.validate.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  </head>
  <body>

todo/templates/todo/index.html
{% include "todo/header.html"%}

<!--  <body> -->
    <div class="container">
      <h1 class="text-center">TODO</h1>
      <a href="new"><button class="btn btn-success" type="button" name="button">New todo</button></a>
      <hr>

      <div class="todoes_list">
        {% if recent_todoes %}
          <ul>
            {% for todo in recent_todoes %}
              {% if todo.todo_done %}
                <li><h4><a href="{% url 'todo:detail' todo.id %}">{{ todo.todo_text }}</a><span style="margin-left:15px" class="glyphicon glyphicon-ok" aria-hidden="true"></span></h4></li>
              {% else %}
                <li><h4><a href="{% url 'todo:detail' todo.id %}">{{ todo.todo_text }}</a></h4></li>
              {% endif %}
            {% endfor %}
          </ul>
          {% else %}
            <h5 class="text-center">No todoes available.</h5>
          {% endif %}
      </div>

    </div>

  </body>
</html>

todo/templates/todo/new.html
{% include 'todo/header.html' %}

<div class="container">
  <h1 class="text-center">Add todo</h1>
  <form action="{% url 'todo:new' %}" method="post" id="new_todo_form">
    {% csrf_token %}
    <input class="form-control" type="text" name="todo_text" autocomplete="off">
    <br>
    <div class="col-md-6">
      <input class="btn btn-success form-control" type="submit" value="Add">
    </div>
  </form>
  <div class="col-md-6">
    <a href="../"><button class="btn btn-info" type="button" name="button">Back</button></a>
  </div>

</div>

<script>
  $(function(){
    $("#new_todo_form").validate({
      rules:{
        todo_text:{
          required:true,
          maxlength:50,
        },
      },
      messages:{
        todo_text:{
          required:"Enter the todo!",
          maxlength:"Max 50 characters!"
        }
      }
    });
  });
</script>

</body>
</html>

todo/templates/todo/update.html
{% include "todo/header.html"%}

<div class="container">
  <h1 class="text-center">Update todo {{ todoID }}</h1>
  <p><label>Original todo: </label> {{ todo_text }}</p>
  <form action="{% url 'todo:update' todoID %}" method="post" id="update_todo_form">
    {% csrf_token %}
    <input class="form-control" type="text" name="todo_text" autocomplete="off" placeholder="New todo...">
    <br>
    <div class="col-md-6">
      <input class="btn btn-success form-control" type="submit" value="Update">
    </div>
  </form>
  <div class="col-md-6">
    <a href="{% url 'todo:detail' todoID %}"><button class="btn btn-info" type="button" name="button">Back</button></a>
  </div>

</div>

<script>
  $(function(){
    $("#update_todo_form").validate({
      rules:{
        todo_text:{
          required:true,
        },
      },
      messages:{
        todo_text:{
          required:"Enter the todo!",
        }
      }
    });
  });
</script>

  </body>
</html>